### ISSUE TITLE
插件无法记录导随(国际服)

### ISSUE THREAD

**Issue by MMMaoxp** [StarHeartHunt/RouletteRecorder#2]
前两天nga提过这个问题，今天开了调试模式进行测试。
在调试模式下写入csv信息不影响，但是并没有信息。目前个人初步怀疑是日志信息本身就是空白。
插件版本24.5.11.539，客户端为英文，ACT正常
![image](https://github.com/StarHeartHunt/RouletteRecorder/assets/160940823/0b5eb68c-4c16-4b62-b345-b194ffe74e95)
此外暂时没有在act文件夹其他可能的位置找到其他形式的日志文件。
![image](https://github.com/StarHeartHunt/RouletteRecorder/assets/160940823/77fa590e-3692-43bf-b3d0-e892eddd59c6)

**Comment by StarHeartHunt** [comment]
能提供一下解析插件的日志吗，如果不方便发这里的话也可以加我dc https://discord.com/invite/wAmWhTyb

或者发我邮箱starheart233@gmail.com

**Comment by MMMaoxp** [comment]
当然可以发，不过目前问题是，不是特别清楚你需要的是哪份文件。
是上传logs用的.log文件吗，如果上传错误最好能说明一下对应的文件路径。
PS：昨天的.log文件有35M无法上传，换了一个今天的十几M可能会方便一些。应该不影响，日志页都是空白
[Network_26909_20240517.log](https://github.com/StarHeartHunt/RouletteRecorder/files/15345283/Network_26909_20240517.log)

**Comment by StarHeartHunt** [comment]
尝试一下release的最新版本[v24.5.17.51](https://github.com/StarHeartHunt/RouletteRecorder/releases/tag/v24.5.17.51)，24.5.11.539还是6.58h1的opcode所以插件没解析出来包

**Comment by MMMaoxp** [comment]
更新后可用，感谢。
考虑到opcode的问题，不知能否实现及时提醒更新版本的功能。此外，如果版本更新只是更改opcode，不涉及其他内容的情况下，是否可以考虑在调试模式下增加手动提供新opcode的功能

**Comment by StarHeartHunt** [comment]
> 更新后可用，感谢。 考虑到opcode的问题，不知能否实现及时提醒更新版本的功能。此外，如果版本更新只是更改opcode，不涉及其他内容的情况下，是否可以考虑在调试模式下增加手动提供新opcode的功能

之后可以考虑联网下载新的opcode在程序内更新
