### ISSUE TITLE
请求添加7.0的新职业

### ISSUE THREAD

**Issue by LittleNightmare** [StarHeartHunt/RouletteRecorder#3]
ClassJob的表里，41是`蝰蛇剑士`，42是`绘灵法师`。我根据前面看了下，应该是符合的

PS：礼问有没有Dalamud插件版本？

**Comment by StarHeartHunt** [comment]
https://github.com/StarHeartHunt/RouletteRecorder/commit/febde7335da36bc32aec3eca8ad2c93024c851fb 加上了
卫月版目前没有，但是刚刚看了一下可能实现起来还要更简单，因为卫月做了副本状态变更事件的封装，这几天可以写一个出来

**Comment by StarHeartHunt** [comment]
https://github.com/StarHeartHunt/RouletteRecorder.Dalamud 卫月版

**Comment by LittleNightmare** [comment]
好耶 ~~不用担心忘记开act了~~
